### PR TITLE
Remove %preun to fix package removal

### PR DESCRIPTION
**Pull request by mthomos**
Fix package removal

### CODE REVIEW

**Comment by pp3345** [comment]
Hi @mthomos,

thanks for your pull request. Could you expand on what precisely this commit fixes? How is package removal currently broken?

**Comment by mthomos** [comment]
Without this PR, when you try to remove package, it fails with this error

error: %preun(dptf-8.4.10401-1.fc30.pp3345.x86_64) scriptlet failed, exit status 1

**Comment by AgentOak** [comment]
@pp3345 Any update on this? I desperately need this fix.

**Comment by pp3345** [comment]
I've pushed https://github.com/pp3345/intel-dptf-fedora/commit/ec6777434729380fc3ae214e9c93e3c6bee055f1 as a proper fix for the issue. Thanks for reporting this bug.

**Comment by pp3345** [comment]
You may use
```
sudo rpm --erase --nopreun dptf
```
to manually remove the package.

**Pull request closed without merging**
